# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8b8bd351c472fc0501af9f6fbb9f8c517f361f6a4b35edb40074b6d75cd83061fc57855662ef214a75741f966e7546373261488cb64dcf1308512c82c36d1c8

test:
  secret_key_base: 2bce77c70ae6e74d2e2b8f6454ab22969ab307ba62db4ffb3bbd74cfc9d56311940d34c0f63753fb5bee405ee180b9ca1ed5ab808afb659910959f14f9fc5a97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
